from __future__ import annotations

LATENCY_WINDOW_5MIN_SECONDS: int = 300
LATENCY_WINDOW_1HR_SECONDS: int = 3_600
ERROR_WINDOW_SECONDS: int = 60
RESOURCE_WINDOW_SECONDS: int = 60
VOLUME_BASELINE_WINDOW_SECONDS: int = 3_600
VOLUME_SPIKE_RATIO_THRESHOLD: float = 3.0

STATISTICAL_ROLLING_WINDOW_SIZE: int = 300
STATISTICAL_SIGMA_CAP: float = 6.0

ISOLATION_FOREST_N_ESTIMATORS: int = 200
ISOLATION_FOREST_MAX_SAMPLES: str = "auto"
ISOLATION_FOREST_CONTAMINATION: float = 0.15
ISOLATION_FOREST_RANDOM_STATE: int = 42

AUTOENCODER_EPOCHS: int = 50
AUTOENCODER_BATCH_SIZE: int = 512
AUTOENCODER_LEARNING_RATE: float = 1e-3
AUTOENCODER_EARLY_STOPPING_PATIENCE: int = 5
AUTOENCODER_RECONSTRUCTION_PERCENTILE: float = 99.0

ROLLING_WINDOW_MINUTES: int = 1
ROLLING_WINDOW_MIN_HISTORY_SAMPLES: int = 7
ROLLING_WINDOW_NEUTRAL_SCORE: float = 0.5

TRACE_STATE_MAX_ENTRIES: int = 10_000

NO_PRIOR_EVENT_SECONDS: float = 9_999.0
MAX_SECONDS_SINCE_LAST_LOG: float = 3_600.0

TOP_CONTRIBUTING_FEATURES_COUNT: int = 3
SHAP_KERNEL_BACKGROUND_SAMPLES: int = 100

GMM_N_COMPONENTS: int = 8
GMM_RANDOM_STATE: int = 42
GMM_REG_COVAR: float = 1e-2

GMM_N_INIT: int = 3

RANDOM_FOREST_N_ESTIMATORS: int = 300
RANDOM_FOREST_MAX_DEPTH: int = 12
RANDOM_FOREST_RANDOM_STATE: int = 42

LIGHTGBM_N_ESTIMATORS: int = 300
LIGHTGBM_LEARNING_RATE: float = 0.05
LIGHTGBM_MAX_DEPTH: int = 8
LIGHTGBM_RANDOM_STATE: int = 42

SCORER_MODEL_DIR_ENV_VAR: str = "LOGSENTINEL_MODEL_DIR"
SCORER_DEFAULT_MODEL_DIR: str = "models/module2"
SCORER_SERVICE_GRAPH_ENV_VAR: str = "LOGSENTINEL_SERVICE_GRAPH_CONFIG"

